# Generated by Django 5.2.5 on 2025-08-17 22:37

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalKnowledge",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "knowledge_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("link", "Link"),
                            ("quote", "Quote"),
                            ("folder", "Folder"),
                            ("article", "Article"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("workspace", "Workspace"),
                            ("org", "Organization"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=50,
                    ),
                ),
                ("attachment", models.TextField(blank=True, max_length=100, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical knowledge",
                "verbose_name_plural": "historical knowledges",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "knowledge_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("link", "Link"),
                            ("quote", "Quote"),
                            ("folder", "Folder"),
                            ("article", "Article"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("workspace", "Workspace"),
                            ("org", "Organization"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=50,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
