# Generated by Django 5.2.5 on 2025-08-17 22:37

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalknowledge",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalknowledge",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="knowledge",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="knowledge.knowledge",
            ),
        ),
        migrations.AddField(
            model_name="knowledge",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_knowledge", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="knowledge",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="historicalknowledge",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="knowledge.knowledge",
            ),
        ),
    ]
